"""Shared pronunciation and teaching definitions (general American English)."""


def term(label, ipa, meaning, explanation, spoken=None):
    return dict(label=label, ipa=ipa, meaning=meaning, explanation=explanation,
                spoken=spoken or label)


GLOSSARY = {
    'ai': term('AI', '/ˌeɪ ˈaɪ/', '人工智能', '让计算机完成识别、预测、生成或决策等任务的一类技术；本课主要讨论基于语言模型的系统。', 'A I'),
    'llm': term('LLM', '/ˌel el ˈem/', '大语言模型', 'Large Language Model：从大量语言材料中学习规律，根据输入生成后续内容。它可以归纳和推断，但输出仍需核实。', 'L L M'),
    'large_language_model': term('Large Language Model', '/lɑːrdʒ ˈlæŋɡwɪdʒ ˈmɑːdəl/', '大语言模型', '擅长处理与生成语言的模型。可以把它看成读过很多资料的写作助手，但不能据此假定它掌握当前业务事实。'),
    'agent': term('Agent', '/ˈeɪdʒənt/', '智能体', '能够围绕目标，调用工具并根据执行结果继续采取行动的 AI 系统。报销时可读取票据、核对规则、整理异常，再交由人员确认。'),
    'multi_agent': term('Multi-Agent', '/ˌmʌlti ˈeɪdʒənt/', '多智能体', '多个具有各自职责、输入或工具边界的智能体共同完成任务；可以使用同一个底层模型。', 'multi agent'),
    'model': term('Model', '/ˈmɑːdəl/', '模型', '通过训练得到的计算系统。模型负责产生预测或内容；工具执行、状态保存和授权还需要周边程序。'),
    'prompt': term('Prompt', '/prɑːmpt/', '提示词／输入指令', '告诉模型任务、材料、约束和输出要求的输入。它能引导行为，但不能代替程序权限控制。'),
    'context': term('Context', '/ˈkɑːntekst/', '上下文', '模型本次请求实际收到的指令、历史、文档与工具结果。没有传入的文件，不能假定模型已经读过。'),
    'context_window': term('Context Window', '/ˈkɑːntekst ˈwɪndoʊ/', '上下文窗口', '一次请求可处理的信息容量，通常以 token 衡量；支持很长的输入也不等于每处细节都能被可靠利用。'),
    'token': term('Token', '/ˈtoʊkən/', '文本处理单位', '模型处理文本时使用的小片段。一个词可能拆成多个 token，中文字符与 token 也不是固定的一对一关系。'),
    'training': term('Training', '/ˈtreɪnɪŋ/', '训练', '使用数据调整模型参数。把公司制度放进一次对话属于提供上下文，并不自动修改模型参数。'),
    'inference': term('Inference', '/ˈɪnfərəns/', '模型推理／运行生成', '用已经训练好的模型处理当前输入并生成结果；术语中的“推理”不保证结果逻辑正确。'),
    'hallucination': term('Hallucination', '/həˌluːsɪˈneɪʃən/', '幻觉／无依据生成', '模型生成看似可信却缺少事实依据或与证据矛盾的内容，例如编造不存在的报销制度条款。'),
    'rag': term('RAG', '/ræɡ/', '检索增强生成', 'Retrieval-Augmented Generation：先检索相关资料，再把资料交给模型生成回答；检索命中和答案引用都需核对。', 'rag'),
    'retrieval': term('Retrieval', '/rɪˈtriːvəl/', '检索', '根据问题找出相关记录或文档片段；找到相似材料不代表材料适用于当前问题。'),
    'embedding': term('Embedding', '/ɪmˈbedɪŋ/', '向量表示', '把文本等内容转换为一组数，以便比较相似性。语义相近不等于事实相同或来源可靠。'),
    'tool': term('Tool', '/tuːl/', '工具', '宿主程序允许模型请求的具体能力，例如查询费用、读取文件或运行测试；实际执行由程序完成。'),
    'tool_calling': term('Tool Calling', '/tuːl ˈkɔːlɪŋ/', '工具调用', '模型提出工具名称和参数，程序校验、执行后把结果交回。模型说“已查询”不能代替实际调用记录。'),
    'function_calling': term('Function Calling', '/ˈfʌŋkʃən ˈkɔːlɪŋ/', '函数调用', '用约定格式请求某个函数；通常是工具调用的一种接口形式，需要宿主验证和执行。'),
    'api': term('API', '/ˌeɪ piː ˈaɪ/', '应用程序接口', '程序间约定的调用方式，例如查询订单接口。连接成功不等于拥有所有数据或写入权限。', 'A P I'),
    'react': term('ReAct', '/riˈækt/', '推理与行动交替', 'Reasoning + Acting：根据已有信息决定动作，调用工具，读取观察结果，再决定下一步。此处不是前端 React 框架。', 'ree act'),
    'reasoning': term('Reasoning', '/ˈriːzənɪŋ/', '推理／判断过程', '利用信息形成判断或下一步选择。本课查看可验证的决定和工具证据，不能把界面摘要当作完整内部思维。'),
    'thought': term('Thought', '/θɔːt/', '思考／决策提示', '流程图中表示决定下一步的阶段；课堂文字是教学说明或决策摘要。'),
    'action': term('Action', '/ˈækʃən/', '行动／工作步骤', '一次可执行的操作；在 MetaGPT 中也指封装具体工作的框架组件。'),
    'observation': term('Observation', '/ˌɑːbzərˈveɪʃən/', '观察／工具返回结果', '工具实际返回的记录或错误。失败也是需要处理的观察，不能被改写成成功。'),
    'plan_execute': term('Plan & Execute', '/plæn ənd ˈeksɪkjuːt/', '规划与执行', '先拆分任务，再执行并检查；约束变化或步骤失败时可修订剩余计划。', 'plan and execute'),
    'planner': term('Planner', '/ˈplænər/', '规划者', '负责拆分任务、安排依赖和验收条件的角色。计划只是待执行安排，不是已经完成的证据。'),
    'executor': term('Executor', '/ɪɡˈzekjətər/', '执行者', '按照计划或当前分派执行工作，并返回实际结果的组件或角色。'),
    'reflection': term('Reflection', '/rɪˈflekʃən/', '反思／复盘', '依据失败和反馈调整后续做法；仅重复要求模型“仔细想想”不保证产生新证据。'),
    'reflexion': term('Reflexion', '/rɪˈflekʃən/', '一种利用语言反馈改进行为的方法', '课程借其说明基于反馈修订方案的思路；本课计划修订示例不等同于完整复现论文方法。'),
    'router': term('Router', '/ˈruːtər/', '路由器／分流器', '按规则或模型判断把请求送到合适的处理入口。本课技能路由使用关键词规则。'),
    'skill': term('Skill', '/skɪl/', '技能', '针对一类任务组织的指令、步骤、工具用法与参考资料；加载技能不等于重新训练模型。'),
    'reference': term('Reference', '/ˈrefərəns/', '参考资料', '完成任务时按需读取的说明、规范或样例；是否适用仍要核对版本和场景。'),
    'blackboard': term('Blackboard', '/ˈblækbɔːrd/', '黑板／共享工作区', '角色在共同状态中发布成果，再按资料就绪条件触发后续工作。需要管理版本和重复触发。'),
    'state': term('State', '/steɪt/', '状态', '本次任务已经知道和已经完成的信息，如预算、证据、当前草稿、版本与待处理问题。'),
    'memory': term('Memory', '/ˈmeməri/', '记忆', '系统为后续步骤保存、筛选并重新提供的信息。普通聊天历史、持久状态和模型参数是不同的存储方式。'),
    'graph': term('Graph', '/ɡræf/', '图／流程图', '用节点表示工作，用边表示允许的执行关系；图可以包含条件、并行和回路。'),
    'workflow': term('Workflow', '/ˈwɜːrkfloʊ/', '工作流', '由程序定义步骤与流转条件的执行过程。节点可以调用模型，也可以全由普通代码完成。'),
    'node': term('Node', '/noʊd/', '节点', '图中的一个工作单元，例如查询天气、调用模型或检查预算。'),
    'edge': term('Edge', '/edʒ/', '边／执行连接', '规定完成当前节点后可以走向哪里；条件边根据状态选择出口。'),
    'dag': term('DAG', '/dæɡ/', '有向无环图', '边有方向且不能沿边回到原节点的图。需要反复修订时，不能把整个循环称作 DAG。', 'dag'),
    'supervisor': term('Supervisor', '/ˈsuːpərvaɪzər/', '主管／调度者', '集中检查任务状态、选择下一个成员并整合结果的角色。'),
    'hierarchical': term('Hierarchical', '/ˌhaɪəˈrɑːrkɪkəl/', '层次化的', '按总负责人、团队负责人、成员分层委派；增加管理边界，也增加交接成本。'),
    'swarm': term('Swarm', '/swɔːrm/', '群体／角色交接模式', '本课指由当前角色按允许的关系移交任务的模式；不意味着所有角色同时执行。'),
    'handoff': term('Handoff', '/ˈhændɔːf/', '交接／控制权移交', '把下一步处理责任及必要信息交给另一角色；应说明交给谁、缺什么、已经做了什么。'),
    'sequential_chain': term('Sequential Chain', '/sɪˈkwenʃəl tʃeɪn/', '顺序链', '外层按预设顺序依次执行工作；若要退回前一步，需要显式设计回路。'),
    'network': term('Network', '/ˈnetwɜːrk/', '网络／对等协作', '由节点按允许的连接选择后继角色；全连接只是可能的一种拓扑。'),
    'parallel': term('Parallel', '/ˈpærəlel/', '并行的', '互不依赖的工作可以同时进行；结果汇合时仍要处理等待、错误和冲突。'),
    'researcher': term('Researcher', '/rɪˈsɜːrtʃər/', '资料研究员／收集者', '本课负责请求工具、收集出游资料的角色。'),
    'analyst': term('Analyst', '/ˈænəlɪst/', '分析员', '本课负责核算费用和检查预算约束的角色。'),
    'writer': term('Writer', '/ˈraɪtər/', '撰写者', '根据已有证据形成可读报告的角色，不能为补齐报告而编造数据。'),
    'critic': term('Critic', '/ˈkrɪtɪk/', '审查者', '检查当前方案是否符合约束、是否仍有缺项的角色。'),
    'framework': term('Framework', '/ˈfreɪmwɜːrk/', '开发框架', '提供组织代码和运行任务的通用组件；领域规则、数据与验收仍由团队实现。'),
    'maf': term('MAF', '/ˌem eɪ ˈef/', 'Microsoft Agent Framework 的缩写', '微软的 Agent 与工作流开发框架；这里为便于讲课逐字母读出缩写。', 'M A F'),
    'microsoft_agent_framework': term('Microsoft Agent Framework', '/ˈmaɪkroʊsɔːft ˈeɪdʒənt ˈfreɪmwɜːrk/', '微软智能体开发框架', '提供 Agent、工具和工作流等构建能力，具体语言与版本的支持范围需核对文档。'),
    'langgraph': term('LangGraph', '/læŋ ɡræf/', '基于状态图组织执行的框架', '用状态、节点和边组织执行；持久化、暂停恢复与外部写入的幂等性需要配置和设计。', 'Lang Graph'),
    'metagpt': term('MetaGPT', '/ˈmetə ˌdʒiː piː ˈtiː/', '按角色和标准流程组织协作的框架', '通过角色、行动和消息传递产物。本课实现代码评审与修复流程。', 'Meta G P T'),
    'ag2': term('AG2', '/ˌeɪ dʒiː ˈtuː/', '一个多智能体协作框架的名称', '课程用其在线示例辅助观察协作机制；实际操作以网站当时展示的示例为准。', 'A G two'),
    'playground': term('Playground', '/ˈpleɪɡraʊnd/', '交互试验场', '用来试用模型或协作流程的演示界面。网站示例与本地程序的模型、数据和执行路径可能不同。'),
    'sdk': term('SDK', '/ˌes diː ˈkeɪ/', '软件开发工具包', '供程序调用框架或服务的一组库与工具。不同语言 SDK 的功能不一定同步。', 'S D K'),
    'checkpoint': term('Checkpoint', '/ˈtʃekpɔɪnt/', '检查点', '保存可恢复的执行状态；恢复前还要确定任务标识、版本和已发生的外部操作。'),
    'interrupt': term('Interrupt', '/ˌɪntəˈrʌpt/', '中断／暂停等待', '在指定位置暂停执行，等待人工决定或外部信息，再按恢复机制继续。'),
    'idempotency': term('Idempotency', '/ˌaɪdemˈpoʊtənsi/', '幂等性', '同一个操作重复提交时，产生的业务效果与一次提交一致。例如重试报销提交不能重复付款。'),
    'sop': term('SOP', '/ˌes oʊ ˈpiː/', '标准作业流程', 'Standard Operating Procedure：明确谁在什么条件下接收什么材料、完成什么工作、交付什么产物。', 'S O P'),
    'role': term('Role', '/roʊl/', '角色', '某项职责及其输入、工具和输出边界；角色名称本身不能提供权限隔离。'),
    'team': term('Team', '/tiːm/', '团队', '共同完成任务的一组角色及其运行环境。'),
    'host': term('Host', '/hoʊst/', '宿主程序', '承载模型与工具的应用程序，负责执行调用、管理状态和落实权限；MCP 中是管理客户端的应用。'),
    'pm': term('PM', '/ˌpiː ˈem/', '产品经理（本课语境）', '本课整理任务看板需求和验收要求的角色。', 'P M'),
    'architect': term('Architect', '/ˈɑːrkɪtekt/', '架构师', '把需求整理成模块、接口和依赖设计的角色。'),
    'developer': term('Developer', '/dɪˈveləpər/', '开发者', '编写或修改代码并提交可检验产物的角色。'),
    'review': term('Review', '/rɪˈvjuː/', '评审', '对照需求、代码与证据检查问题；形式完整的意见仍可能误判。'),
    'reviewer': term('Reviewer', '/rɪˈvjuːər/', '评审者', '独立检查变更并给出定位、证据和修复建议的角色。'),
    'tester': term('Tester', '/ˈtestər/', '测试者', '运行或组织验证并记录实际结果的角色；测试覆盖之外仍可能存在缺陷。'),
    'artifact': term('Artifact', '/ˈɑːrtɪfækt/', '产物', '可保存、传递和复核的工作结果，如需求文档、代码文件、评审记录和测试报告。'),
    'pr': term('PR', '/ˌpiː ˈɑːr/', '代码合并请求', 'Pull Request：提交一组代码变更供团队评审；本课不自动向代码平台发起或合并请求。', 'P R'),
    'pull_request': term('Pull Request', '/pʊl rɪˈkwest/', '代码合并请求', '请维护者检查并合并一组代码变更的协作对象，通常附带差异、讨论和检查结果。'),
    'diff': term('Diff', '/dɪf/', '差异／代码变更对照', '展示两个版本中增加、删除或改变的内容；需要结合调用方和需求判断影响。'),
    'contract': term('Contract', '/ˈkɑːntrækt/', '契约／输入输出约定', '明确接受哪些输入、返回哪些字段以及如何报告错误，供实现与验收共同遵守。'),
    'schema': term('Schema', '/ˈskiːmə/', '结构定义', '规定字段、类型和必填项。符合结构只说明格式有效，不代表字段里的事实正确。'),
    'json': term('JSON', '/ˈdʒeɪsən/', '一种结构化数据格式', '用对象、数组等表示数据，便于程序读取和校验；字符串仍可能包含错误或恶意内容。', 'Jason'),
    'revision': term('Revision', '/rɪˈvɪʒən/', '修订版本', '一次代码或产物变更后的版本标记；评审、测试和批准应指向同一版本。'),
    'ci': term('CI', '/ˌsiː ˈaɪ/', '持续集成', 'Continuous Integration：代码变更后自动执行构建和检查的流程；检查项目与权限仍需配置。', 'C I'),
    'a2a': term('A2A', '/ˌeɪ tə ˈeɪ/', '智能体之间的互操作协议', 'Agent-to-Agent：让不同系统中的智能体描述能力、交换任务信息和结果；不自动替代身份认证与业务授权。', 'A to A'),
    'mcp': term('MCP', '/ˌem siː ˈpiː/', '模型上下文协议', 'Model Context Protocol：约定应用如何发现和使用服务器提供的工具、资源与提示模板。', 'M C P'),
    'model_context_protocol': term('Model Context Protocol', '/ˈmɑːdəl ˈkɑːntekst ˈproʊtəkɔːl/', '模型上下文协议', '标准化模型应用接入外部能力的交互方式；并非模型本身，也不负责保证业务答案正确。'),
    'agent_card': term('Agent Card', '/ˈeɪdʒənt kɑːrd/', '智能体能力卡片', '描述能力、入口及认证等信息，类似服务说明书；卡片声明仍需在实际调用中验证。'),
    'task': term('Task', '/tæsk/', '任务', '有身份、状态和结果的一项工作，例如一份代码评审任务。'),
    'message': term('Message', '/ˈmesɪdʒ/', '消息', '角色或系统之间交换的信息；需要区分请求、资料、反馈和结束信号。'),
    'client': term('Client', '/ˈklaɪənt/', '客户端', '按协议发起交互的一方；在 MCP 中，宿主应用通过客户端连接服务器。'),
    'server': term('Server', '/ˈsɜːrvər/', '服务器／服务端', '按协议提供能力的一方；可运行在本机，也可运行在远端。'),
    'resource': term('Resource', '/ˈriːsɔːrs/', '资源', '供应用读取的上下文材料，例如文件内容或业务记录；具体访问范围取决于服务配置。'),
    'prompt_injection': term('Prompt Injection', '/prɑːmpt ɪnˈdʒekʃən/', '提示注入', '外部材料夹带指令，试图让系统偏离用户任务或越权，例如网页要求模型泄露密钥。'),
    'guardrail': term('Guardrail', '/ˈɡɑːrdreɪl/', '防护措施／护栏', '输入检查、权限限制、输出验证和运行预算等约束的统称，不能只依赖一句提示词。'),
    'sandbox': term('Sandbox', '/ˈsændbɑːks/', '沙箱／隔离执行环境', '限制代码可访问的文件、网络和资源的环境；普通子进程或超时设置本身不等于安全沙箱。'),
    'timeout': term('Timeout', '/ˈtaɪmaʊt/', '超时', '超过允许的等待或执行时间后终止等待、报错或转入恢复路径。'),
    'retry': term('Retry', '/ˌriːˈtraɪ/', '重试', '失败后再执行一次操作；应限制次数，并确认重复执行不会造成重复扣款等副作用。'),
    'latency': term('Latency', '/ˈleɪtənsi/', '延迟／耗时', '从请求发起到得到结果所需的时间；平均值之外也要关注较慢的一批请求。'),
    'baseline': term('Baseline', '/ˈbeɪslaɪn/', '基线／对照方案', '用来比较收益和成本的初始方案，例如规则工作流或单智能体。'),
    'evaluation': term('Evaluation', '/ɪˌvæljuˈeɪʃən/', '评测', '在明确任务集与通过标准下检查质量、成本和速度，不能只看一次成功演示。'),
}

PRONUNCIATION_NOTE = ('音标以常见美式读法为主；品牌、组合词和缩写采用课堂便于交流的读法，'
                      '不表示唯一官方读音。播放声音由浏览器和系统的英语语音决定。')
