(function () {
  'use strict';
  const {cards, callout, table, code, notes, slide} = N5.content;
  N5.chapters.push({id: 8, title: '收尾', slides: [
    slide('P49', '交付选型卡：模型具体负责哪项判断？', 120,
      table(['按顺序问','对应机制'],[['① 动作与分支已能用规则确定？','先用确定性工作流；工具结果未知也不例外'],['② 需要模型解释新观察，再选下一动作？','在限定工具、次数与验收边界内使用 ReAct'],['③ 需要按本次目标生成步骤与依赖计划？','Plan-and-Execute；计划中的诊断可局部 ReAct'],['④ 失败证据否定了计划假设或依赖？','Reflexion / Replan；修订后重新取得验收证据']]) + cards([['另做分工判断','上下文、工具权限或专业责任确需隔离，再权衡拆分收益与协调成本。'],['一分钟填卡','任务：____　选择：____<br>理由：____　不选：____　验收：____']],2),
      notes('先看普通规则是否已经能决定动作。前端固定发布检查即使有异步工具结果，也无需模型控制流程。只有需要解释新证据决定下一步时，才增加 ReAct；只有需要把本次目标转化为依赖计划时，才增加 Planner。两者可以嵌套，无法只凭步骤多少判断。分工是另一轴：同一种策略可以在单角色或多角色系统内使用。卡片的理由须指向具体模型判断，验收须指向证据与条件；框架名称不能替代它们。', '任选 Java 延迟排查、Android SDK 迁移或前端发布，先说哪个动作需要模型判断；如果全部能规则化，能否明确选择不引入 Agent？', '二十秒复习四问，六十秒填选型卡，四十秒抽一张：核对选择理由、排除方案和验收条件。若同学只写“任务复杂所以多 Agent”，请其补出独立权限或专业责任。', '下一页只补契约中的一个关键缺口；完整设计留到课后练习并按参考答案评分。')),
    slide('P50', '工程实操：补一条消息，或一个失败出口', 180,
      '<p class="small">发布候选检查助手：目标 commit B、构建 hB、任务 r42；只输出建议。任选一种故障补全规则。</p>' + code('已给：from=test_reviewer → to=supervisor，intent=report\n待补：run_id / task_id / plan_version / commit_sha / artifact_sha256 / evidence_refs\n退出规则：收到 ______ 时，由 ______ 写入 ______；后续消息必须 ______。') + table(['故障注入','你的规则需要回答'],[['① 目标 B，测试报告却来自 A','拒收还是通过？哪些检查需要重跑？'],['② 页面重建，原任务仍在运行','复用哪个任务？怎样避免重复创建？'],['③ 已确认取消，迟到“成功”到达','谁维护终态？怎样拒绝过期更新？']]) + '<p class="small"><button type="button" data-handout="contract">查看参考契约与评分</button>　课堂补一处；完整契约留作课后 10 分钟练习。</p>',
      notes('课堂三分钟只练局部：三十秒读输入，六十秒选一项补消息或失败出口，六十秒同伴说明，三十秒打开参考答案核对。核心路线两分钟为二十秒读题、五十秒补写、五十秒核对。不要把这一次短练习计作已经独立完成整个系统设计。故障一应拒收旧提交证据并补当前候选的缺失检查；故障二应保存并复用 run_id，页面重新观察同一任务，界面重建本身不触发服务端任务取消；故障三由宿主维护不可倒退的终态，迟到响应不能覆盖已确认取消。Android 应同时绑定 commit_sha、artifact_sha256、build_variant 和设备/API 环境；同提交的 debug 与 release 性能报告不能直接互用。配置变更可通过 ViewModel 保留观察入口，进程恢复还需按需求保存任务标识；停止收集 Flow 不等于取消远端任务。课后完整十分钟练习：两分钟写选型理由与验收；两分钟补角色、权限和一次交接消息；两分钟列共享字段、写入者及证据版本；两分钟推演三个故障与资源上限；两分钟对照参考契约评分并补缺口。允许用确定性工作流或单 Agent，只要解释充分。任务状态与发布建议分开：检查已完成但发现阻断项，可写 COMPLETED + BLOCK；缺证据、执行失败、超限和取消均不能伪装成可发布。', '目标仍为 B，能否把 A 的“测试全过”当作 B 的证据？页面旋转时，取消的是界面观察还是服务端任务？请任选一项写成宿主能执行的规则。', '先保留参考答案关闭，让每人补一处；再点击“查看参考契约与评分”核对字段、证据与终态。将完整契约作为课后交付，记录还缺哪条规则，不用三分钟练习宣称已经掌握完整协作设计。', '带走选型卡和待补契约，并用参考资料核对概念与实现边界。'),{coreSeconds:120}),
    slide('P51', '参考资料与使用边界', 60,
      table(['主题','官方 / 原始资料'],[['ReAct · Reflexion','<a href="https://arxiv.org/abs/2210.03629" target="_blank" rel="noopener">ReAct 论文</a> · <a href="https://arxiv.org/abs/2303.11366" target="_blank" rel="noopener">Reflexion 论文</a>'],['Plan-and-Execute · LangGraph','<a href="https://blog.langchain.com/planning-agents/" target="_blank" rel="noopener">Planning agents</a> · <a href="https://docs.langchain.com/oss/python/langgraph/overview" target="_blank" rel="noopener">LangGraph 文档</a>'],['AutoGen · 新项目评估','<a href="https://github.com/microsoft/autogen" target="_blank" rel="noopener">AutoGen 仓库</a> · <a href="https://learn.microsoft.com/agent-framework/" target="_blank" rel="noopener">Microsoft Agent Framework</a>'],['MetaGPT','<a href="https://github.com/FoundationAgents/MetaGPT" target="_blank" rel="noopener">MetaGPT 仓库与 README</a>']]) + callout('离线是预设教学剧本；真实模式仍使用合成工具数据。本课不实现生产权限、持久恢复或审批系统。') + '<p class="small">框架 API、维护声明和 Python 范围已于 2026-09-23 核对官方资料，采用前再核对目标版本；公开决策摘要不代表模型内部思维。</p>',
      notes('最后再次说明证据边界：能完整播放的脚本证明了教学过程可演示，不证明真实模型在任意输入下可靠；真实模式使用合成数据，也不代表生产系统已经集成。代码检视复审是规则演示，不等于实际编译、单测、压测或安全审计。资料链接供课后深入阅读，维护状态和依赖范围以采用当时的官方信息为准。', '请每位学员写一句话：下次设计 Agent 时，首先会明确哪一个验收条件？', '显示参考链接，告知讲师稿有逐页操作与问答；离线课堂无需现场打开外部网站。', '课程结束。以明确的责任、可追溯的事实和可检查的结束条件开始下一次实现。'))
  ]});
})();
